# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend
#   namespace: roboshop
#   labels:
#     project: roboshop
#     tier: frontend
#     component: frontend
# data:
#   MONGO: "true"
#   MONGO_URLL: "mongodb://mongodb:27017/frontend"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: frontend
    component: frontend
spec:
  replicas: 1
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: frontend
      component: frontend
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:1.4.0
        imagePullPolicy: Always
        # Readiness: Don't send traffic until the port is open
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "150m"
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
    # Liveness: Restart if the port becomes unresponsive
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 20
          failureThreshold: 5
        # envFrom:
        # - configMapRef:
        #     name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    tier: frontend
    component: frontend
spec:
  type: LoadBalancer
  selector:
    # labels are used as selectors
    project: roboshop
    tier: frontend
    component: frontend
  ports:
  - protocol: TCP
    port: 80 # servie port
    targetPort: 80 # container port

