apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    project: user
    tier: backend
    component: user
data:
  MONGO: "true"
  REDIS_URL: "'redis://redis:6379'"
  MONGO_URLL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  # these labels are replicaset labels
  labels:
    project: user
    tier: backend
    component: user
spec:
  replicas: 1
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: user
      tier: backend
      component: user
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: user
        tier: backend
        component: user
    spec:
      containers:
      - name: user
        image: joindevops/user:1.4.0
        imagePullPolicy: Always
        # Readiness: Don't send traffic until the port is open
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "150m"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
    # Liveness: Restart if the port becomes unresponsive
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 20
          failureThreshold: 5
        envFrom:
        - configMapRef:
            name: user
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    project: user
    tier: backend
    component: user
spec:
  selector:
    # labels are used as selectors
    project: user
    tier: backend
    component: user
  ports:
  - protocol: TCP
    port: 8080 # servie port
    targetPort: 8080 # container port

